name: asl_counters
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  #logic
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  stream_transform: ^2.1.0
  
  # ui
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  
  # json
  json_annotation: ^4.9.0
  meta: ^1.12.0

  #network
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
flutter_intl:
  enabled: true